version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_sales
      - name: raw_footfall
      - name: raw_change_index
      - name: raw_stores
      - name: raw_areas
      - name: raw_district_clusters
